### ISSUE TITLE
issues while setting ip address

### ISSUE THREAD

**Issue by cpankonien** [G6EJD/ESP8266-Remote-Message-Board#10]
I've tried to update the ip address of the webserver so that it is on the same subnet as the rest of my devices, but it does not work once I do that. I have updated the ssid, password, ip address and gateway address but I am then unable to access it. (I can access the webserver I use my phone, join the "message board" network, then go to 192.168.4.1) There are references to "softAPconfig" - "This address may be changed by softAPconfig", but I can't find any other reference to softAPConfig, or how to change the ip address using it. If I am missing something obvious please accept my apologies; I've been a network technician since 1995 so I am very familiar with that world, but I am definitely not a programmer! Thanks!

**Comment by G6EJD** [comment]
https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/soft-access-point-class.html

You can set any address you like, well within reason and not using an address already assigned.

**Comment by cpankonien** [comment]
ok, thanks, looks like I'm missing a big piece of the puzzle, thanks!

**Comment by G6EJD** [comment]
In the documentation you will see methods to set all the network settings, dns, subnet, ip that will solve your problem, however with none of those set it will join your network once it has a WiFi connection and should work without issues. Let me know if you have any more problems.

**Comment by cpankonien** [comment]
Yes, I'm slowly working through the process. In fact it may be better for me to use it as-is. I am trying to create a sort of led "license plate" for my bicycle that will automatically obtain the artist name and song name of whatever song is playing at the time on my bluetooth speaker and display that info like "now playing - jethro tull, a passion play". So I may try using an nfc tag on my bike so that when activated by the nfc chip, my phone (Google Pixel 4) will connect to the nodemcu on 192.168.4.1 and (somehow) push (or nodemcu pulls) artist, song data, etc. In this case there is no value to using anything other than what already works, so why mess with it? Right now I am pondering how to "inject" the artist and song data into your app...any ideas or suggestions welcome! 

Thanks...

**Comment by cpankonien** [comment]
Using your sketch as-is, I am able to bring up the web page and enter a message, but it doesn't seem to update the esp8266, the "Welcome..." message on the esp8266 doesn't change. I also see nothing at the serial monitor when I upload the new message, not sure if that is normal or not? Am I doing something wrong, or is it not intended to work in the way I am trying?

**Comment by G6EJD** [comment]
This is where it's probably going wrong:
  webpage += "<form action=\"http://" + IPaddress + "\" method=\"POST\">";
It needs the input method for that mode to be changed..

**Comment by cpankonien** [comment]
the only thing i could find that resembled that line is

webpage += "<FORM action='getmessageinput'>";

so I changed that to

webpage += "<form action="http://" + IPaddress + "" method="POST">";

but that didn't work, as I'm sure you are not surprised.

Unfortunately I have no idea what to change, or what to change it from/to.
I've googled it, and used to do rudimentary html forms back in 1998 or so,
but me and programming these days is like a dog watching tv....it's
interesting but I have no idea what is going on. If I'm asking too much I
understand completely, thanks for your patience.

**Comment by G6EJD** [comment]
I was sat here thinking I’m sure I solved this problem before, so I checked the code here and I did:
https://github.com/G6EJD/ESP8266-Remote-Message-Board/blob/master/ESP_Message_Board_V21.ino

**Comment by G6EJD** [comment]
And: https://github.com/G6EJD/ESP8266-Remote-Message-Board/blob/master/ESP_Message_Board_V3.ino

using the latest webserver

**Comment by cpankonien** [comment]
So...I've tried both the updated v2.1 and v3.0. After adding the correct
libraries I was able to successfully compile and upload each. I was then
able to access the webserver on 192.168.4.1, and submit a message, but the
message does not appear on the led matrix. With updated v2.1, the message
on the display remains "Welcome..."
With v3.0, the led display freezes. (I did have to change #include <WiFi.h>
to #include <ESP8266WiFi.h> to get it to compile successfully.
I first suspected that the pin assignments were incorrect but as far as I
can tell, they are correct, the same as the version that displays
successfully, even if it only displays "Welcome...".
Thanks!

**Comment by G6EJD** [comment]
Try V3.0 again, I've added a diagnostic print and watch the serial monitor to see if the entered message is displayed.

**Comment by cpankonien** [comment]
on compiling revised code, I get these errors:

/home/cliff/Arduino/sketch_feb11c/sketch_feb11c.ino: In function 'void
getmessageinput()':
sketch_feb11c:126:14: error: 'class AsyncWebServer' has no member named
'args'
   if (server.args() > 0 ) { // Arguments were received
              ^
sketch_feb11c:127:37: error: 'class AsyncWebServer' has no member named
'args'
     for ( uint8_t i = 0; i < server.args(); i++ ) {
                                     ^
sketch_feb11c:128:39: error: 'class AsyncWebServer' has no member named
'argName'
       String Argument_Name   = server.argName(i);
                                       ^
sketch_feb11c:129:39: error: 'class AsyncWebServer' has no member named
'arg'
       String client_response = server.arg(i);
                                       ^
Multiple libraries were found for "Max72xxPanel.h"
 Used: /home/cliff/Arduino/libraries/arduino-Max72xxPanel-master
 Not used: /home/cliff/Arduino/libraries/ESP8266-Remote-Message-Board-master
exit status 1
'class AsyncWebServer' has no member named 'args'

Not sure how you make any sense out of all that, but I'm glad that you do!

**Comment by G6EJD** [comment]
There was a problem, please try again. Yes sounds like we have similar interests.

**Comment by cpankonien** [comment]
Compiled successfully (once wifi.h is changed to esp8266wifi.h, hope that's
the correct thing to do). Also changed pin values to suit, namely pinCS=4,
MOSI(DIN)=7, CLK=5. Led display blank. Successfully submitted message from
192.168.4.1, nothing noted at console. (I assume we're talking about the
console screen at the bottom of the arduino ide screen?)

**Comment by G6EJD** [comment]
Serial port monitor

**Comment by cpankonien** [comment]
I've been trying to do this very thing for some time now with no success
(PEBKAC I'm guessing). I've tried a few different serial port monitors
available on Linux (interceptty, minicom, socat) to no avail. Every time I
start the upload it fails due to "read failed: device reports readiness to
read but returned no data (device disconnected or multiple access on port?)
does not exist or your board is not connected. Boy do I feel like a n00b.
I'll keep looking though.

**Comment by G6EJD** [comment]
In the IDE you go Tools, then in the Port section, you will see the port used to programme the device, but you want Tools, Serial Monitor, press the rest and it will show the esp start-up, etc, then the serial.port printing of the variable message

**Comment by cpankonien** [comment]
oh, I was way off, that's pretty cool. It looks like the "Welcome..."
message is repeating; when I send something from 192.168.4.1, nothing
happens, just keeps doing the "Welcome..." message. Thanks for the shove in
the right direction! (I'm guessing I should have seen whatever message I
sent from webserver...)

**Comment by G6EJD** [comment]
Next put a diagnostic print in the getinout function to see if it gets a new message value, something like serial.println(“New message = “ + String(message)); 

i can’t see why it’s not working

**Comment by cpankonien** [comment]
Unfortunately I have no idea how or where to do that. I've looked for the
getinout function, it's not obvious to me where that is or how I would do
what you suggest. Also looked at anything that says "serial.println" but
again, there are a few, and I don't know which to change or add to. At the
very least though, I am able to upload a message and it will display on the
rear of my bike, so that's pretty cool. Maybe I'll just pick a long song
for each ride and have it display that song, so it will at least be correct!

**Comment by G6EJD** [comment]
I thought it wasn’t working sounds like it is, now your trying to pass song names to it, now that’s on a different level.

**Comment by cpankonien** [comment]
OK...version 2.1 will display a message that I type in to replace the
"Welcome..." message. Version 3 doesn't display anything. I am trying to
get to the point so that I can reliably send a message from the web server
and have it display on the led matrix. If I get to that point, then I will
look at trying to "scrape" the app I use to play music (or maybe there's an
api, I haven't checked at this point) for the artist and song title, and
pass that to the web server for display on the led matrix. Sorry if I threw
some confusion in there. So...version 2.1 compiles, uploads and displays
the message that is added manually to the sketch, but does not update with
any message from the web server. Version 3 compiles and uploads, but does
not display anything, nor does it accept input from the web server (but the
webserver does start and accept input normally. Hope that makes sense...

**Comment by G6EJD** [comment]
I've just compiled and tested v3.1 which is identical to 3, but I've uploaded it again to be sure, its working perfectly.
You are connecting your PC or WHY to the network called 'message board' then starting a browser and entering 192.168.4.1 to get the home screen?
No issues found with 3.1

**Comment by cpankonien** [comment]
Yes, that is correct. I connect to the SSID "messageboard", then open
chrome browser and browse to 192.168.4.1. I enter a message in the message
box and hit the send message button. I have connected with both a Google
Pixel 4 and a Chromebook, identical results with both. I'll compile and
upload 3.1 and let you know how it goes.

**Comment by cpankonien** [comment]
got a bunch of errors - "sketch_feb11e:91:31: error:
'AsyncWebServerRequest' has not been declared".

Not sure why it works for you and not me...I must be doing something wrong,
but damned if I know what that could be. Anyway, thanks for the efforts.

**Comment by G6EJD** [comment]
You have t installed the asynchronous webserver library and its accompanying extension

**Comment by cpankonien** [comment]
It's becoming obvious that my lack of knowledge is hindering progress. I'm
going to make a concerted effort to learn how to program specifically for
esp8266, since they are cheap and seem to be able to do a lot of cool
things. Also I am retired so I have plenty of time on my hands. Hopefully
I'll be able to return to this project soon. Thanks for your patience and
efforts. If there are any resources you think might help the learning
curve, please share!

Cheers,

cliff
