### ISSUE TITLE
Debugging ESP8266_MAX7219_Message_Board_AP.ino:71: error: 'GetMEssage'

### ISSUE THREAD

**Issue by LenK13** [G6EJD/ESP8266-Remote-Message-Board#4]
Hello, I'm trying to use your code and example using my NodeMCUESP8266 and MAX7219. But I'm having trouble compiling the code.  I have followed all the steps referenced at

 "http://www.whatimade.today/build-a-remote-controlled-dot-matrix-message-board-in-10-minutes-with-just-two-inexpensive-components/". 

I am hoping for some insight, support, help for an error message I am getting while attempting to duplicate "G6EJD/ESP8266-Remote-Message-Board" using a Amica NodeMCUESP8266 and the Max7219 Dot Matrix. 
Error Message is posted here. 

" ESP8266_MAX7219_Message_Board_AP.ino:71: error: 'GetMEssage' was not declared in this scope

   server.on("/",GetMEssage); "

Thank you in advance, for your help

**Comment by G6EJD** [comment]
The character case error is a nuisance but it does not affect compilation as both instances have the same ‘error’ and you can call them anything you like e.g. ‘gEtMeSsAGe’ it will still work. 
The reason for your compilation error is almost certainly a missing ‘}’,
Start from the top and place your cursor on the first { the ide will indicate where the closing } is it should be at the end of setup then the same for loop and any functions until you find the error.

**Comment by G6EJD** [comment]
I've corrected the spelling error, all it needed was to change GetMEssage to GetMessage.

I have complied all three version and they work without issue.
