### ISSUE TITLE
remove scroll

### ISSUE THREAD

**Issue by jasondreher** [G6EJD/ESP8266-Remote-Message-Board#7]
sorry not an issue but asking is there any way to remove the scroll? i just want a message to show on the display.

**Comment by G6EJD** [comment]
There Is an issue in by doing this, because power consumption will increase as you have static led’s. Have you tried reducing the message length down to 4 characters?

**Comment by jasondreher** [comment]
Yes, if I just write “hi” it scrolls. I am looking for something to use as a countdown timer. Thought I could http post a new time each second as it counts down. I would http post with a home automation software Calle HomeAssistant.

**Comment by G6EJD** [comment]
Modify display message:
    while ( x + width - spacer >= 0 && letter >= 0 ) {
      if ( letter < message.length() ) {
        matrix.drawChar(x, y, message[letter], HIGH, LOW, 1); // HIGH LOW means foreground ON, background OFF, reverse these to invert the display!
      }
      letter--;
      x -= width;
    }
    matrix.write(); 
~~~~~~~~~
matrix.drawChar(x-3, y, message[letter], HIGH, LOW, 1); 
matrix.drawChar(x-2, y, message[letter], HIGH, LOW, 1); 
matrix.drawChar(x-1, y, message[letter], HIGH, LOW, 1); 
matrix.drawChar(x-0, y, message[letter], HIGH, LOW, 1); 
matrix.write();

**Comment by jasondreher** [comment]
cant seem to get it to work, trying to modify https://www.hackster.io/FilippoOnesti/esp8266-clock-using-max7219-led-matrix-display-b036c7 now as that has time that does not scroll
