### ISSUE TITLE
softAP issue?

### ISSUE THREAD

**Issue by phanny-pack** [G6EJD/ESP8266-Remote-Message-Board#8]
Hello! May not be an issue and just misuse on my part, but when inputting in the webpage and entering any message, the LED matrix won't update for me, locally or through wifi. It seems my ESP's server works fine (I was able to find that and connect to it, and typing that into my browser brings up the webpage). However, how does that connect to the softAP server we are creating? is that the reason the message isn't updating for me? Lmk if you need me to send picture examples or something, thank you so much for your hard work, this is a really neat project
![image](https://user-images.githubusercontent.com/50034721/101238343-6c010d00-3694-11eb-8610-ad4ced81a496.png)
^^ here i can see that the serial monitor is updating, but each update doesn't show a received argument? Initially the "Setting soft-AP configuration..." showed "... Failed!" so I tried playing around with different IP configs using the example one in the softAP documentation until it marked as "Ready". Still no difference

**Comment by G6EJD** [comment]
What you should do is confirm the message board is getting g a connection from say your pc client, you can programme the board from your IDE and monitor the serial port watching for a connection request and connected. Then when you type a message to be displayed there is a variable that contains the text entered, is it getting that, next is that variable being transferred to the variable used for display. Send me your code or is it verbatim log this version?

**Comment by G6EJD** [comment]
OK so the variable 'message' is what is being updated are you seeing an input field to enter the new message?

**Comment by phanny-pack** [comment]
Hello, thanks for replying! I was assuming next to the 0: in the serial monitor would display the message received, since that seems to update every 60 seconds as you set it. The code is mostly verbatim, but you can check here, the only thing I changed is the softAP section:
` void setup() {
  Serial.begin(115200); // initialize serial communications
  //WiFi.softAP(ssid);
  //The network established by softAP will have default IP address of 192.168.4.1. This address may be changed using softAPConfig.
  IPAddress local_IP(192, 168, 4, 22); // Use the same adress here as defualt softAP
  IPAddress gateway(192, 168, 4, 9);
  IPAddress subnet(255, 255, 255, 0);
  Serial.print("\rSetting soft-AP configuration ... ");
  Serial.println(WiFi.softAPConfig(local_IP, gateway, subnet) ? "Ready" : "Failed!");
  WiFi.softAP(ssid);
  Serial.print(F("Use this URL to connect: http://")); Serial.println(WiFi.softAPIP().toString() + "/"); // Print the IP address

  //----------------------------------------------------------------------
  server.on("/",GetMessage);
  server.begin(); Serial.println(F("Webserver started...")); `

![image](https://user-images.githubusercontent.com/50034721/101262830-3ee54680-36f6-11eb-8df3-985d6c4ff936.png)

Here I tried changing the local_IP and gateway. Before, using the default softAP local IP and gateway that you set, the output on serial monitor was "checking softAP configuration ... Failed!". So when i changed it to the local IP and gateway in the above image (using defaults from an example on the softAP documentation) it finally said "Ready" (which i'm unsure if that is the problem at all). I double checked to confirm that I can connect to my specific board's IP on a separate PC on the same WIFI, and was able to pull up the webpage created:

![image](https://user-images.githubusercontent.com/50034721/101262898-aa2f1880-36f6-11eb-9625-9d55f4af3fd2.png)

As you can see, I can see the input field and am able to click on the "Enter Message" button, but the board doesn't seem to register the input. The IP address I entered in my browser on the top is the one my board is using, with the :8266 extension since I want to use this across the web (lol its a gift for my gf, want to send her cool messages)

**Comment by G6EJD** [comment]
I think this is where it’s going wrong when using a softAP: 
String IPaddress = WiFi.softAPIP().toString();

I think it’s not picking up the IP address to then use for the input, I’ll have a look at it for you.

**Comment by phanny-pack** [comment]
Thanks for looking into it! In case it helps, when I try inspecting the webpage, it shows this error in the console: 
![image](https://user-images.githubusercontent.com/50034721/101263245-b87e3400-36f8-11eb-9408-cb2769c65f76.png)

**Comment by G6EJD** [comment]
Are you using port 1 ?
e.g. 192.168.0.16:1
As the get IP address function won’t get a port number

**Comment by G6EJD** [comment]
I can see in the ide port:1

**Comment by phanny-pack** [comment]
Where in the IDE are you seeing port 1? Sorry i can't see it :(

**Comment by G6EJD** [comment]
It may be a facet of the IDE on the bottom line but if you check the connected IP address it is 192.168.1.71:8266
But in the IDE it’s using: 192.168.4.22 this is why it’s not working.

**Comment by phanny-pack** [comment]
I see. So if I changed the softAP local IP to 192.168.1.71 it should work? I tried and it doesn't :( do you know what I should change the gateway to?

**Comment by G6EJD** [comment]
I've now made extensive changes to the code, it works without any issues using softAP.

I have removed the need for a IP address for the Form action element by adding an additional server command to handle inputs.

I have also reduced the size of the code and validated all the HTML using the W3C Validator.

**Comment by phanny-pack** [comment]
Thank you so so much, you made my holidays! Ik it must have taken a lot of time looking through this so thank you so so much for your help, I hope you have a good one!

**Comment by G6EJD** [comment]
Ok happy to help.
