### ISSUE TITLE
if message length is 60 characters long it does not accept

### ISSUE THREAD

**Issue by cvraosan** [G6EJD/ESP8266-Remote-Message-Board#9]
Hi I have changed to ESP32 from ESP8266
and used your new code but still there is some issue
if the message is 60 characters long it does not accept from the web page

message ="Welcome..1234567890a1234567890b1234567890c1234567890d1234567890e1234567890f";

**Comment by G6EJD** [comment]
size='50'

**Comment by G6EJD** [comment]
This is an HTML facet not a code issue, time to learn about HTML 🙂
The maximum string size is about 16384 bytes and the maximum HTML input size is usually limited by the browser to 2048 chars

**Comment by cvraosan** [comment]
You are the guru here -- but we need to enter longer messages so we need to look at a solution

**Comment by cvraosan** [comment]
there is an issue
![image](https://user-images.githubusercontent.com/75560317/101284902-80fead00-3808-11eb-82cb-0daca1e4df03.png)

then we cannot enter any message -- however small into the html page

**Comment by cvraosan** [comment]
![image](https://user-images.githubusercontent.com/75560317/101284969-d63abe80-3808-11eb-8f23-b13cd61258e2.png)

then we cannot enter any message -- however small into the HTML page -- it is not an HTML issue

**Comment by G6EJD** [comment]
You have to wait for message to finish otherwise it spends all its time sending the message and never responds to the webserver clients request

**Comment by cvraosan** [comment]
The code is very good -- but if the welcome message is long even 50 characters -- this has nothing to do with the HTML input size since this message is basically bit mapped to the led array --the HTML web page does not respond when you type a message

**Comment by G6EJD** [comment]
I have made further changes. You must monitor the Serial port of the ESP to see what's going on. You can't send two messages to the display when it's already processing as message, this stops the webserver from responding.

I have just tried it again and can send really long messages, no detectable limit for me.

I have also added an Asynchronous Webserver version is is using the later webserver code. The same restrictions apply.

If you need to send two messages in sequence then you will have to code a flag something like 'sending = true' and set it when the code enters the display function and reset when it comes out of the display function, then test this 'sending' flag outside and if true then don't send another message yet until it is false. 

Your example looked commercial in its nature to me, is this for a commercial application sign?

**Comment by cvraosan** [comment]
1. thanks for the two messages flag method 
2. I will check the code again
3. it is not for commercial purposes -- just a test message

**Comment by cvraosan** [comment]
perfecto -- now it works  ---thanks a lot

**Comment by G6EJD** [comment]
👍
